name: Build and Deploy Hello World Node.js App

on:
  push:
    branches:
      - main

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image
        run: docker build . -t hello-world-node

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.hub.docker.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker image
        run: docker tag hello-world-node ${{ secrets.DOCKERHUB_USERNAME }}/hello-world-node:latest

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-world-node:latest

      - name: Run Docker container
        run: docker run -d -p 3000:3000 hello-world-node

      - name: Verify deployment
        run: curl -s http://localhost:3000 | grep "Hello World"
